# Generated by Django 4.2.16 on 2026-04-27 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LugarConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del lugar')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del lugar')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden en listas')),
            ],
            options={
                'verbose_name': 'Lugar de consulta',
                'verbose_name_plural': 'Lugares de consulta',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='recordatorio_canal',
            field=models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('ambos', 'WhatsApp y Email')], max_length=10, verbose_name='Canal usado'),
        ),
        migrations.AddField(
            model_name='cita',
            name='recordatorio_enviado',
            field=models.BooleanField(default=False, verbose_name='Recordatorio enviado'),
        ),
        migrations.AddField(
            model_name='cita',
            name='recordatorio_fecha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío'),
        ),
        migrations.AddField(
            model_name='cita',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='agenda.lugarconsulta', verbose_name='Lugar de consulta'),
        ),
    ]
