# Generated by Django 4.2.16 on 2026-04-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, help_text='Opcional — se usará para recordatorios por correo', max_length=254, verbose_name='Email'),
        ),
    ]
