# Generated by Django 4.2.16 on 2026-04-27 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_lugarconsulta_cita_recordatorio_canal_and_more'),
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='agenda.lugarconsulta', verbose_name='Lugar de consulta'),
        ),
    ]
